base_url = "https://www.ant-lab.tw"

theme = "Ergo"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "1337"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# RSS
title = "Ant Lab"
description = "A space to record things I explore"
generate_rss = true
# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = []


[extra]
profile = 'me.jpg'
website = "www.ant-lab.tw"
github = "yanganto"
facebook = "yanganto"
twitter = "__yanganto__"
email = "yanganto@gmail.com"
linkin = "yanganto"
cv = "cv.pdf"
#instagram = "${your_insta}"
#youtube = "${your_youtube_channel_id}"
